# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecf1461498f980507aeb116a604ecf0da198dc5283c8a57a083b27ae9d25fc713ab92485a1c6983c1bd0897abc60b71dd3d3a6ed896f312cb26088d9563db463

test:
  secret_key_base: 94a62bd458b18c1f59db969ee60660d6455e00cd0a1e7a29bc180567add566c3c4ebd7c863f9c12a777c669ea1872d0993dfae489ccad0197ced61f2da78ea28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
